%% INICIALIZACIÓN DE BUSES DE DATOS
% Este script se ejecuta al inicializar el modelo del sistema.
% Genera los enums:
% - EstadoValvula
% - ActuadorPosicionado
% - ParametroControl
% - ModoControl
% - Controlador
% Genera los buses de datos:
% - actuadorBus (array con instancias del bus "actuador")
% - sistema
% - regulador
% Estos buses portan la información necesaria de configuración y estado a
% las distintas etapas del proceso.
% Cuando se genera un array de structs, es necesario convertirlo a un array
% de buses mediante 'Simulink.Bus.createMATLABStruct' para que Simulink
% pueda interpretarlo correctamente con los bloques 'For Each Subsystem'.

clear;

%% CONFIGURACIÓN MANUAL

% ACTUADORES
% Número de actuadores conectados al sistema
numAct = 4;

% REGULADOR
configuracionTerminalControl = 1;
configuracionTerminalRealimentacion = 1;
configuracionTerminalesCurvatura = [2,3,4,5];

% ELECTROVÁLVULAS
% Terminales de conexión: puertos de la DAQ (tarjeta de adquisición de
% datos) a los que se encuentran conectados los terminales A y B de la
% electroválvula de cada actuador.
configuracionTerminalesA = [
    5, ... % Actuador 1, pin 1  Marrón-Blanco
    7, ... % Actuador 2, pin 2  Marrón
    1, ... % Actuador 3, pin 3  Verde-Blanco
    3 ...  % Actuador 4, pin 4  Azul
    ];
configuracionTerminalesB = [
    6, ... % Actuador 1, pin 14 Naranja-Blanco
    8, ... % Actuador 2, pin 15 Naranja
    2, ... % Actuador 3, pin 16 Naranja-Blanco
    4 ...  % Actuador 4, pin 17 Naranja
    ];
% Ruta al subsistema de conexión con las entradas y salidas de la tarjeta
% de adquisición de datos, para la configuración automática de puertos.
DAQ_path = 'ControlSystem_Refactorization/Hardware/DAQ';

%% ENUMS

Simulink.defineIntEnumType('EstadoValvula', ... 
	{'Bloquear', 'Inyectar', 'Expulsar'}, ...
	[0;1;2], ... 
	'Description', 'Flujo de aire desde el regulador hasta el actuador a través de la válvula', ...
	'DefaultValue', 'Bloquear', ...
	'HeaderFile', 'myvalvestates.h', ...
	'DataScope', 'Exported', ...
	'AddClassNameToEnumNames', true, ...
	'StorageType', 'uint8');

Simulink.defineIntEnumType('ActuadorPosicionado', ...
    {'Posicionado', 'Desposicionado', 'Control_Manual'}, ...
    [0;1;2], ...
    'Description', 'Estado del actuador respecto a la referencia deseada', ...
    'DefaultValue', 'Desposicionado', ...
    'HeaderFile', 'act_position.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('ParametroControl', ...
    {'Presion', 'Curvatura'}, ...
    [0;1], ...
    'Description', 'Medida de referencia elegida para el control del actuador', ...
    'DefaultValue', 'Presion', ...
    'HeaderFile', 'referencia_control.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('ModoControl', ...
    {'Manual', 'Autonomo_Secuencial'}, ...
    [0;1], ...
    'Description', 'Sistema de control activo', ...
    'DefaultValue', 'Manual', ...
    'HeaderFile', 'modo_control.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

Simulink.defineIntEnumType('Controlador', ...
    {'Presion', 'Curvatura', 'EquilibrioPresiones'}, ...
    [0;1;2], ...
    'Description', 'Controlador seleccionado', ...
    'DefaultValue', 'Presion', ...
    'HeaderFile', 'controlador.h', ...
    'DataScope', 'Exported', ...
    'AddClassNameToEnumNames', true, ...
    'StorageType', 'uint8');

%% ACTUADORES
actuador = repmat(struct( ...
    'Configuracion', struct( ...
        'Global', struct( ...
            'activo', false, ...
            'indice', 0, ...
            'Referencia', struct( ...
                'presion', 0, ...
                'curvatura', 0 ...
            ) ...
        ), ...
        'ControlManual', struct('estadoValvula', EstadoValvula.Bloquear) ...
    ), ...
    'Estado', struct( ...
        'ControlAutomatico', struct( ...
            'estadoValvula', EstadoValvula.Bloquear, ...
            'actuadorPosicionado', ActuadorPosicionado.Desposicionado), ...
        'Realimentacion', struct('presion', 0, 'curvatura', 0) ...
    ) ...
), numAct, 1);

% Asignar el índice correspondiente a cada uno de los actuadores
for act = 1:numAct
    actuador(act).Configuracion.Global.indice = act;
end

% Crear el objeto de bus basado en la estructura
actuadorBusInfo = Simulink.Bus.createObject(actuador);
slBusActuador = evalin('base', actuadorBusInfo.busName);

% Crear un array de buses a partir del array de structs
actuadorBus = arrayfun(@(x) Simulink.Bus.createMATLABStruct(actuadorBusInfo.busName, x), actuador);

% Guardar el array de buses en el workspace de Simulink
assignin('base', 'actuadorBus', actuadorBus);


%% SISTEMA
sistema = struct( ...
    'Configuracion', struct( ...
        'Global', struct( ...
            'numActuadores', numAct, ...
            'modoControl', ModoControl.Manual, ...
            'parametroControl', ParametroControl.Presion, ...
            'referenciaControl', double(0), ...
            'controlador', Controlador.Presion, ...
            'simulacionActiva', 0, ...
            'toleranciaEquilibrioPresiones', 0, ...
            'ToleranciaPresion', struct( ...
                'estacionaria', 0, ...
                'derivativa', 0 ...
            ), ...
            'ToleranciaCurvatura', struct( ...
                'estacionaria', 0, ...
                'derivativa', 0 ...
            ) ...
        ), ...
        'ControlManual', struct( ...
            'actuadorSeleccionado', 0 ...
        ) ...
    ), ...
    'Estado', struct( ...
        'Global', struct( ...
            'realimentacionControl', double(0), ...
            'errorEstacionario', double(0), ...
            'errorDerivativo', double(0) ...
        ), ...
        'ControlAutomatico', struct( ...
            'actuadorSeleccionado', 0 ...
        ) ...
    ) ...
);

% Crear el objeto de bus basado en la estructura
sistemaBusInfo = Simulink.Bus.createObject(sistema);
slBusSistema = evalin('base', sistemaBusInfo.busName);

%% REGULADOR
regulador = struct( ...
    'Estado', struct( ...
        'presion', 0 ...
    ) ...
);

% Configurar automáticamente los bloques 'AnalogOutput' y 'AnalogInput' con
% los terminales de conexión configurados
set_param(strcat(DAQ_path,'/Analog Output'), 'Channels', mat2str(configuracionTerminalControl));
set_param(strcat(DAQ_path,'/Analog Input'), 'Channels', mat2str(configuracionTerminalRealimentacion));
set_param(strcat(DAQ_path,'/Analog Input1'), 'Channels', mat2str(configuracionTerminalesCurvatura));

if numel(unique(configuracionTerminalesCurvatura)) ~= numAct
    error(['Error: el número de terminales definidos para leer los sensores de curvatura ', ...
        'no se corresponde con el número de actuadores en uso.']);
end

% Crear el objeto de bus basado en la estructura
reguladorBusInfo = Simulink.Bus.createObject(regulador);
slBusRegulador = evalin('base', reguladorBusInfo.busName);

%% ELECTROVÁLVULAS
% Definición de "electroValvulas"
electroValvulas = struct( ...
    'Configuracion', struct( ...
        'ConexionActuadores', repmat(struct( ...
            'terminalA', uint16(0), ...
            'terminalB', uint16(0) ...
        ), numAct, 1), ... % Array con numAct elementos
        'PuertosDigitales', uint16([]) ... % Lista inicialmente vacía
    ) ...
);

% Asignación de terminales y puertos digitales a cada uno de los actuadores
for act = 1:numAct
    electroValvulas.Configuracion.ConexionActuadores(act).terminalA = uint16(configuracionTerminalesA(act));
    electroValvulas.Configuracion.ConexionActuadores(act).terminalB = uint16(configuracionTerminalesB(act));
end

% Verificar si hay valores repetidos en terminalA o terminalB
% 1. Obtener lista de valores de terminalA y terminalB
listaTerminales = [ ...
    [electroValvulas.Configuracion.ConexionActuadores.terminalA], ...
    [electroValvulas.Configuracion.ConexionActuadores.terminalB] ...
];
% 2. Verificar duplicados
if numel(unique(listaTerminales)) < numel(listaTerminales)
    error(['Error: Se han detectado puertos repetidos en los terminales de control de las electroválvulas.', ...
        newline, ...
        'Asegúrate de que cada puerto se encuentra conectado a un único terminal, ', ...
        'y de que todos los actuadores están correctamente conectados a dos terminales A y B de la misma electroválvula.']);
end

% Actualizar "PuertosDigitales" con los puertos digitales utilizados de la
% DAQ
puertosDigitales = unique(listaTerminales, 'sorted');
electroValvulas.Configuracion.PuertosDigitales = puertosDigitales;

% Configurar automáticamente el bloque 'Digital Output' con los puertos
% seleccionados
set_param(strcat(DAQ_path,'/Digital Output'), 'Channels', mat2str(puertosDigitales));

% Crear el objeto de bus basado en la estructura
electroValvulasBusInfo = Simulink.Bus.createObject(electroValvulas);
slBusElectroValvulas = evalin('base', electroValvulasBusInfo.busName);